### ISSUE TITLE
Example for uniswap-asset-resolver

### ISSUE THREAD

**Issue by Burmenska** [polywrap/polyfolio#124]

**Comment by Burmenska** [comment]
We already got your answer on the May'5:

> You can use contract_address from the response and make a request to uniswap-asset-resolver to fetch the underlying token components and other relevant metadata.

**Comment by Burmenska** [comment]
@Niraj-Kamdar  will provide with the example until EOD, 2022-05-19

**Comment by Burmenska** [comment]
Hi @Niraj-Kamdar  could you please add to method getTransactions https://github.com/defiwrapper/defiwrapper/pull/167/files#diff-8d7c2f94221891752f54732decd821e09317aa708d6564a8d750c02803b5bff1R7 new transaction with Exchange event in log?

**Comment by Brioline** [comment]
The only swap transaction we have in mock, returns 2 components by it's contract address
Both returns error while `tokenInfo` for them
1.
`
"Error: WasmWeb3Api: Wasm module aborted execution.
URI: w3://ipfs/QmP3MZcYiug8YHKet6uDmw13dkV7uMu5wmdmXz7HFgLtUy
Module: query
Method: tokenInfo
Input: {
  "id": "ethereum",
  "contract_address": "_**0x03A5c5f12bD0BbaE973215b1C184FF3cE9942cFc**_"
}
Message: __w3_abort: Result: Unwrap Ok; Error: PluginWeb3Api: invocation exception encountered.
uri: w3://ens/http.web3api.eth
module: query
method: get
resultFilter: undefined
input: {
  "url": "https://api.coingecko.com/api/v3/coins/ethereum/contract/0x03A5c5f12bD0BbaE973215b1C184FF3cE9942cFc",
  "request": {
    "headers": [],
    "urlParams": [],
    "responseType": 0,
    "body": ""
  }
}
modules: {
  "query": {
    "_config": {},
    "_env": {}
  }
}
exception: Request failed with status code 404
File: ~lib/@web3api/wasm-as/containers/Result.ts
Location: [171,13].

    at abort (http://localhost:3000/static/js/bundle.js:64055:21)
    at __w3_abort (http://localhost:3000/static/js/bundle.js:64804:9)
    at http://localhost:3000/static/js/bundle.js:60990:22
    at src/query/w3/entry/w3Abort (wasm://wasm/0011cd82:wasm-function[10]:0x78e)
    at src/query/routes/tokenInfo/tokenInfo (wasm://wasm/0011cd82:wasm-function[164]:0x1cca4)
    at src/query/w3/Query/wrapped/tokenInfoWrapped (wasm://wasm/0011cd82:wasm-function[181]:0x28a30)
    at ~lib/@web3api/wasm-as/invoke/w3_invoke (wasm://wasm/0011cd82:wasm-function[88]:0xb815)
    at src/query/w3/entry/_w3_invoke (wasm://wasm/0011cd82:wasm-function[218]:0x34386)
    at AsyncWasmInstance.<anonymous> (http://localhost:3000/static/js/bundle.js:61061:24)
    at step (http://localhost:3000/static/js/bundle.js:60791:17)"
`

2. [float issue](https://github.com/polywrap/polyfolio/issues/156) for: "**_0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2_**"

**Comment by Niraj-Kamdar** [comment]
1) @Brioline first error is expected since the token specified here seems like a test token with just 3 transactions: https://etherscan.io/address/0x03A5c5f12bD0BbaE973215b1C184FF3cE9942cFc. 

Ignore values in dollar terms for these kinds of tokens since generally, those will have 0 values. It'd be similar in the case of WRAP-IOU since we aren't listed anywhere, it shouldn't have any financial values but can still be found in your portfolio. 


2) The float issue is known and I will try to quick fix it if it isn't possible I will remove it from the mock data
